development:
  access_key_id: 'AKIAICC4PX3DLERBZURQ'  
  secret_access_key: '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'
  bucket: 'cabooseit'

test:
  access_key_id: 'AKIAICC4PX3DLERBZURQ'
  secret_access_key: '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'
  bucket: 'cabooseit'

production:
  access_key_id: 'AKIAICC4PX3DLERBZURQ'
  secret_access_key: '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'
  bucket: 'cabooseit'