development:
  access_key_id: 'mykey'  
  secret_access_key: 'mysecretkey'
  bucket: 'mybucket'

test:
  access_key_id: 'mykey'  
  secret_access_key: 'mysecretkey'
  bucket: 'mybucket'

production:
  access_key_id: 'mykey'  
  secret_access_key: 'mysecretkey'
  bucket: 'mybucket'